#!/bin/bash

start() {
  docker-compose up -d
  echo "Waiting for systemd to start up..."
  sleep 10
  docker-compose exec kube ./init.sh
  docker-compose exec slate helm init --service-account tiller
}

bare() {
  docker-compose up -d
}

pause() {
  docker-compose stop
}

resume() {
  docker-compose start
}

purge() {
  docker-compose down -v
}

address() {
  docker-compose exec kube ip -f inet addr show eth0 | grep -Po 'inet \K[\d.]+' | xargs
}

rebuild() {
  docker-compose build --no-cache $1
}

shell() {
  docker-compose exec $1 /bin/bash
}

slate() {
  docker-compose exec slate slate "$@"
}

if [[ $1 =~ ^(start|pause|resume|purge|address|rebuild|shell|slate)$ ]]; then
  "$@"
else
  echo "Invalid subcommand $1" >&2
  exit 1
fi
